version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecurePassword123
      MYSQL_DATABASE: node_crud_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
      # - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: SuperSecurePassword123
      DB_NAME: node_crud_db
      DB_PORT: 3306
    depends_on:
      - db
    volumes:
      - .:/app


