apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-crud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-crud
  template:
    metadata:
      labels:
        app: nodejs-crud
    spec:
      containers:
      - name: nodejs-crud-container
        image: rajyadav282/syvora:latest
        ports:
        - containerPort: 3000
