name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          image: rajyadav282/syvora
          registry: docker.io
          username: ${{ secrects.DOCKER_USERNAME }}
          password: ${{ secrects.DOCKER_PASSWORD }}
       