# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - master  

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

      

#       - name: Build and Push Docker Image
#         uses: mr-smithers-excellent/docker-build-push@v6
#         with:
#           image: docker-hub-repo/image-name
#           registry: docker.io
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

name: Build and Push Docker image to Docker Hub

on: 
  push:
    branches:
      - master  


jobs:

  push_to_registry:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
       uses: actions/checkout@v3

      

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
           context: Dockerfilefolder
           push: true
           tags: rajyadav282/syvora:latest
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
        
       