name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: my-docker-repo/my-docker-image:${{ github.sha }}
          cache-from: type=registry,ref=rajyadav282/syvora:/my-docker-image:cache
          cache-to: type=registry,ref=rajyadav282/syvora:/my-docker-image:cache,mode=max

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
